version: '3.2'

services:
  symeo-database:
    image: "postgres:13"
    container_name: "symeo-database"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=symeo
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d symeo -h localhost" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - symeo_network

  symeo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=symeo
      - POSTGRES_HOST=symeo-database
      - POSTGRES_PORT=5432
    depends_on:
      symeo-database:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - symeo_network

networks:
  symeo_network:
    driver: bridge
